### ISSUE TITLE
New version not in Cocoapods - cannot update pod to the latest version

### ISSUE THREAD

**Issue by onexip-vanessa** [Clafou/DevicePpi#2]
The latest version (1.2.14) doesn't seem to be published to Cocoapods, which is still on version 1.2.12: [https://cocoapods.org/pods/DevicePpi](https://cocoapods.org/pods/DevicePpi) 
As a result of that, some devices which are already added to the list still only get a best guess PPI.
Please consider publishing the new version to Cocoapods, so that the pod can be updated to the latest version.

**Comment by slajar** [comment]
@Clafou maybe you can link our npm capacitor plugin somewhere? This is on top of your cocoapod :) https://github.com/onexip/capacitor-screen-size

**Comment by Clafou** [comment]
@slajar Thanks, added a link!
If you use this in an app and are happy to share I'd love to know.
